version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    environment:
      - MONGO_URL=mongodb://jnasdkkxxx:12nn22wwr9921312121@mongodatabase:27017/?authSource=admin
      - PORT=3000
      - MONGO_TOKEN=sadasn121344nj010
    depends_on:
      - mongodatabase
  mongodatabase:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=superlongusername
        - MONGO_INITDB_ROOT_PASSWORD=superlonnnnnnnnnngpaswworrrd
volumes:
 mongodb:
  
