name: Security Testing

on:
  push:
    branches: [ "master", "main" ]
  pull_request: {}


jobs:
  security-testing:
    name: security-testing
    uses: affinidi/pipeline-security/.github/workflows/security-scanners.yml@feat-sonarcloud
    permissions:
      contents: read
      security-events: write
      actions: read
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
